#pragma once
#include "../civetweb/CivetServer.h"
#include "GetCSSPages.h"

class CDestinationHandle : public CivetHandler
{
public:

	bool handleGet(CivetServer *server, struct mg_connection *conn)
	{
		//UTF-8 Conversion
		//mg_connection *pComm = (mg_connection*)conn;
		//mg_header *pHeader=(mg_header*)&mg_get_request_info(conn)->http_headers[0];

		//redirection!!
		//mg_send_http_redirect(conn, , 301);

		mg_printf(conn,
			"HTTP/1.1 200 OK\r\nContent-Type: "
			"text/html\r\nConnection: close\r\n\r\n");
		mg_printf(conn,
			"<!DOCTYPE html>\r\n"
			"<html lang=\"ko\">\r\n"
			"<head>\r\n"
			"        <meta charset=\"utf-8\">\r\n"
			"        <style>\r\n");
		mg_printf(conn, GetCSSPages::pPISC);
		mg_printf(conn, GetCSSPages::pDestination);
		mg_printf(conn,	
			"</style>\r\n"
			"    <title>PISC-\xeb\x85\xb8\xec\x84\xa0\xec\x84\xa4\xec\xa0\x95""</title>\r\n"
			"\r\n"
			"</head>\r\n"
			"\r\n"
			"<body onload=\"load()\" oncontextmenu='return false' ondragstart='return false' onselectstart='return false'>\r\n"
			"    <div id=\"container\">\r\n"
			"\r\n"
			"        <header>\r\n"
			"            <img id=\"logo\" src=\"/app/image/Logo.png\" alt=\"\xec\x84\x9c\xec\x9a\xb8\xea\xb5\x90\xed\x86\xb5\xea\xb3\xb5\xec\x82\xac"" \xeb\xa1\x9c\xea\xb3\xa0""\">\r\n"
			"            <span id=\"nowTime\">\r\n"
			"                <p id=\"txtDate\">2020. 02. 04</p>\r\n"
			"                <p id=\"txtTime\">AM 10 : 25 : 30</p>\r\n"
			"            </span>\r\n"
			"            <span id=\"headerTitle\">\xeb\x85\xb8\xec\x84\xa0\xec\x84\xa4\xec\xa0\x95""</span>\r\n"
			"            <hr id=\"headerLine\">\r\n"
			"        </header>\r\n"
			"\r\n"
			"        <section>\r\n"
			"            <button id=\"txtLine\" onclick=\"toggleLineType()\" \"></button> <!-- \xec\x83\x81\xed\x96\x89\xec\x84\xa0""/\xed\x95\x98\xed\x96\x89\xec\x84\xa0"" \xec\x84\xa0\xed\x83\x9d"" -->\r\n"
			"            <br>\r\n"
			"\r\n"
			"            <!-- \xeb\x85\xb8\xec\x84\xa0"" \xec\x84\xa0\xed\x83\x9d"" : \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" -->\r\n"
			"            <table class=\"inforTable\" id=\"stopList\">\r\n"
			"                <!-- DB\xec\x97\x90\xec\x84\x9c"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" \xea\xb0\x80\xec\xa0\xb8\xec\x99\x80\xec\x84\x9c"" \xec\xb6\x9c\xeb\xa0\xa5\xed\x95\xa8"".. -->\r\n"
			"                <!-- <tr><td>001. \xea\xb0\x95\xeb\x8f\x99"" \xe2\x86\x94"" \xeb\xa7\x88\xec\xb2\x9c""</td></tr>\r\n"
			"                <tr><td>002. \xea\xb0\x95\xeb\x8f\x99"" \xe2\x86\x94"" \xec\x83\x81\xec\x9d\xbc\xeb\x8f\x99""</td></tr>> -->\r\n"
			"            </table>\r\n"
			"\r\n"
			"            <!-- \xeb\x85\xb8\xec\x84\xa0"" \xec\x84\xa0\xed\x83\x9d"" : \xec\x8a\xa4\xed\x81\xac\xeb\xa1\xa4"" \xeb\xb2\x84\xed\x8a\xbc"" -->\r\n"
			// "            <table class=\"arrowBtn\">\r\n"
			// "                <tr><td><img src=\"/app/image/UpScroll.png\" alt=\"UP\xeb\xb2\x84\xed\x8a\xbc""\" onclick=\"clickLineUpDn('up', mLineTableId)\" style=\"width:80px\"></td></tr>\r\n"
			// "                <tr><td style=\"height: 60px;\"></td></tr> <!-- Up/Down \xeb\xb2\x84\xed\x8a\xbc"" \xec\x82\xac\xec\x9d\xb4\xec\x97\x90"" \xea\xb3\xb5\xeb\xb0\xb1""  -->\r\n"
			// "                <tr><td><img src=\"/app/image/DownScroll.png\" alt=\"Down\xeb\xb2\x84\xed\x8a\xbc""\" onclick=\"clickLineUpDn('down', mLineTableId)\" style=\"width:80px\"></td></tr>\r\n"
			// "                <!-- <tr><td><button onclick=\"LineScroll('up')\">\xec\x9c\x84""</button></td></tr>\r\n"
			// "                <tr><td style=\"height: 95px;\"></td></tr>  Up/Down \xeb\xb2\x84\xed\x8a\xbc"" \xec\x82\xac\xec\x9d\xb4\xec\x97\x90"" \xea\xb3\xb5\xeb\xb0\xb1""\r\n"
			// "                <tr><td><button onclick=\"LineScroll('down')\">\xec\x95\x84\xeb\x9e\x98""</button></td></tr>  -->\r\n"
			// "            </table>\r\n"
            "           <table class=\"updnBtn\">"
            "               <tr><td><button class=\"upBtn\" onclick=\"clickLineUpDn('up', mLineTableId)\"></button></td></tr>\r\n"
            "               <tr><td style=\"height: 60px;\"></td></tr>\r\n"
            "               <tr><td><button class=\"downBtn\" onclick=\"clickLineUpDn('down', mLineTableId)\"></button></td></tr>\r\n"
            "           </table>\r\n"
			"\r\n"
			"\r\n"
			"            <table class=\"inforTable\" id=\"routeList\">\r\n"
			"                <!-- <tr><td>001. \xec\x8b\x9c\xeb\xb0\x9c"" - \xea\xb0\x95\xeb\x8f\x99""</td></tr>\r\n"
			"                <tr><td>002. \xeb\x8f\x84\xec\xb0\xa9"" - \xeb\x91\x94\xec\xb4\x8c\xeb\x8f\x99""</td></tr>\r\n"
			"                <tr><td>003. \xeb\x8f\x84\xec\xb0\xa9"" - \xec\x98\xac\xeb\xa6\xbc\xed\x94\xbd\xea\xb3\xb5\xec\x9b\x90""</td></tr>\r\n"
			"                <tr><td>004. \xeb\x8f\x84\xec\xb0\xa9"" - \xeb\xb0\xa9\xec\x9d\xb4""</td></tr>\r\n"
			"                <tr><td>005. \xec\xb6\x9c\xeb\xb0\x9c"" - \xec\x9e\x84\xec\x82\xb0\xeb\xb6\x80\xeb\xb0\xb0\xeb\xa0\xa4""</td></tr>\r\n"
			"                <tr><td>006. \xec\xb6\x9c\xeb\xb0\x9c"" - \xec\x9e\x84\xec\x82\xb0\xeb\xb6\x80\xeb\xb0\xb0\xeb\xa0\xa4""</td></tr>\r\n"
			"                <tr><td>007. \xec\xb6\x9c\xeb\xb0\x9c"" - \xec\x9e\x84\xec\x82\xb0\xeb\xb6\x80\xeb\xb0\xb0\xeb\xa0\xa4""</td></tr>\r\n"
			"                <tr><td>008. \xec\x8b\x9c\xeb\xb0\x9c"" - \xea\xb0\x95\xeb\x8f\x99""</td></tr>\r\n"
			"                <tr><td>009. \xeb\x8f\x84\xec\xb0\xa9"" - \xeb\x91\x94\xec\xb4\x8c\xeb\x8f\x99""</td></tr>\r\n"
			"                <tr><td>010. \xeb\x8f\x84\xec\xb0\xa9"" - \xec\x98\xac\xeb\xa6\xbc\xed\x94\xbd\xea\xb3\xb5\xec\x9b\x90""</td></tr>\r\n"
			"                <tr><td>011. \xeb\x8f\x84\xec\xb0\xa9"" - \xeb\xb0\xa9\xec\x9d\xb4""</td></tr>  -->\r\n"
			"            </table>\r\n"
			"\r\n"
			"            <!-- \xeb\xb0\xa9\xec\x86\xa1"" \xeb\xaa\xa9\xeb\xa1\x9d"" : \xec\x8a\xa4\xed\x81\xac\xeb\xa1\xa4"" \xeb\xb2\x84\xed\x8a\xbc"" -->\r\n"
			// "            <table class=\"arrowBtn\">\r\n"
			// "                <tr><td><img src=\"/app/image/UpScroll.png\" alt=\"UP\xeb\xb2\x84\xed\x8a\xbc""\" onclick=\"clickLineUpDn('up', mPaTableId)\" style=\"width:80px\"></td></tr>\r\n"
			// "                <tr><td style=\"height: 60px;\"></td></tr> <!-- Up/Down \xeb\xb2\x84\xed\x8a\xbc"" \xec\x82\xac\xec\x9d\xb4\xec\x97\x90"" \xea\xb3\xb5\xeb\xb0\xb1"" -->\r\n"
			// "                <tr><td><img src=\"/app/image/DownScroll.png\" alt=\"UP\xeb\xb2\x84\xed\x8a\xbc""\" onclick=\"clickLineUpDn('down', mPaTableId)\" style=\"width:80px\"></td></tr>\r\n"
			// "            </table>\r\n"
            "           <table class=\"updnBtn\">"
            "               <tr><td><button class=\"upBtn\" onclick=\"clickLineUpDn('up', mPaTableId)\"></button></td></tr>\r\n"
            "               <tr><td style=\"height: 60px;\"></td></tr>\r\n"
            "               <tr><td><button class=\"downBtn\" onclick=\"clickLineUpDn('down', mPaTableId)\"></button></td></tr>\r\n"
            "           </table>\r\n"
			"\r\n"
			"        </section>\r\n"
			"\r\n"
			"        <footer>\r\n"
			"            <button class=\"rectFootBtn\" id=\"cancBtn\" onclick=\"location.href='menu.html'\">\xec\x9d\xb4\xec\xa0\x84""</button>\r\n"
			"            <button class=\"rectFootBtn\" id=\"okBtn\" onclick=\"confirmSelected('stopList')\">\xed\x99\x95\xec\x9d\xb8""</button>\r\n"
			"        </footer>\r\n"
			"\r\n"
			"    </div>\r\n"
			"    <script>\r\n"
			"        const cTABLE_LIST_NUM = 5;\r\n"
			"        const cLINE_DOWN = 0; \r\n"
			"        const cLINE_UP = 1;\r\n"
			"        var mLineType = 0;\r\n"
			"        var mLineTableId = document.getElementById(\"stopList\");\r\n"
			"        var mPaTableId = document.getElementById(\"routeList\"); \r\n"
			"\r\n"
			"        var mLineData = {\r\n"
			"            \"type\": \"none\",\r\n"
			"            \"count\": 0,\r\n"
			"            \"list\": [\r\n"
			"            ]\r\n"
			"        }\r\n"
			"\r\n"
			"        //var stopData;\r\n"
			"        //var routeData;\r\n"
            "        var selectLine;\r\n"
            "        var selectLineNum;\r\n"
			"\r\n"
			"        var arrControl = [\r\n"
			"         { \"name\": \"stopList\", \"element\": document.getElementById(\"stopList\"), \"querySelector\": \"#stopList tr\", \"selectedLine\": undefined, \"scrollPos\": 0, \"listData\": mLineData },\r\n"
			"         { \"name\": \"routeList\", \"element\": document.getElementById(\"routeList\"), \"querySelector\": \"#routeList tr\", \"selectedLine\": undefined, \"scrollPos\": 0, \"listData\": mLineData },\r\n"
			"        ]\r\n"
			"\r\n"
			"\r\n"
			"        function setLineType(lineType) {\r\n"
			"            switch(lineType)\r\n"
			"            {\r\n"
			"                case 0:\r\n"
			"                    txtLine.innerHTML = \"\xec\x83\x81\xed\x96\x89\xec\x84\xa0""\";\r\n"
			"                    break;\r\n"
			"                case 1:\r\n"
			"                    txtLine.innerHTML = \"\xed\x95\x98\xed\x96\x89\xec\x84\xa0""\";\r\n"
			"                    break;\r\n"
			"            }\r\n"
			"            var info = { name: \"selectedDirection\", value: String(lineType) };\r\n"
			"            var strInfo = JSON.stringify(info);\r\n"
			"            //console.log(strInfo);\r\n"
			"            connection.send(strInfo);\r\n"
			"            return lineType;\r\n"
			"        }\r\n"
			"\r\n"
			"        function toggleLineType()\r\n"
			"        {\r\n"
			"            switch(mLineType)\r\n"
			"            {\r\n"
			"                case 0:\r\n"
			"                    mLineType = 1;\r\n"
			"                    mLineType=setLineType(mLineType);\r\n"
			"                    break;\r\n"
			"                case 1:\r\n"
			"                    mLineType = 0;\r\n"
			"                    mLineType=setLineType(mLineType);\r\n"
			"                    break;\r\n"
			"                default:\r\n"
			"                    break;\r\n"
			"            }\r\n"
			"        }\r\n"
			"\r\n"
			"\r\n"
			"\r\n"
			// "        function scanLineListNum() {\r\n"
			// "            var line = document.querySelectorAll(\"#stopList tr\");\r\n"
			// "            for (var i = 0; i < line.length; i++) {\r\n"
			// "                line[i].onclick = function () { // click \xec\x9d\xb4\xeb\xb2\xa4\xed\x8a\xb8"" \xea\xb8\xb0\xeb\x8b\xa4\xeb\xa6\xbc""..\r\n"
			// "                    if(mSelectedLine!=undefined)\r\n"
			// "                        mSelectedLine.classList.remove(\"select\"); // \xec\x9d\xb4\xec\xa0\x84\xec\x97\x90"" \xec\x84\xa0\xed\x83\x9d\xed\x95\x9c"" \xec\x9a\x94\xec\x86\x8c\xec\x97\x90"" className \xec\x82\xad\xec\xa0\x9c""\r\n"
			// "                    this.className = \"select\"; // \xed\x98\x84\xec\x9e\xac"" \xeb\x88\x84\xeb\xa5\xb8"" \xec\x85\x80\xec\x9d\x84"" class Name 'select'\xeb\xa1\x9c"" \xec\xa4\x8c""\r\n"
			// "                    mSelectedLine = this;\r\n"
			// "                    mSelectedLine.className = \"select\";\r\n"
			// "                    sendSelectedStopPtn(this.id);\r\n"
			// "                };\r\n"
			// "            }\r\n"
			// "        }\r\n"
			"\r\n"
			"        function scanList(arrList) {\r\n"
			"            var line = document.querySelectorAll(arrList.querySelector);\r\n"
			"            for (var i = 0; i < line.length; i++) {\r\n"
			"                line[i].onclick = function () { // click \xec\x9d\xb4\xeb\xb2\xa4\xed\x8a\xb8"" \xea\xb8\xb0\xeb\x8b\xa4\xeb\xa6\xbc""..\r\n"
			"                    if (arrList.selectedLine != undefined)\r\n"
			"                        arrList.selectedLine.classList.remove(\"select\"); // \xec\x9d\xb4\xec\xa0\x84\xec\x97\x90"" \xec\x84\xa0\xed\x83\x9d\xed\x95\x9c"" \xec\x9a\x94\xec\x86\x8c\xec\x97\x90"" className \xec\x82\xad\xec\xa0\x9c""\r\n"
			"                    this.className = \"select\"; // \xed\x98\x84\xec\x9e\xac"" \xeb\x88\x84\xeb\xa5\xb8"" \xec\x85\x80\xec\x9d\x84"" class Name 'select'\xeb\xa1\x9c"" \xec\xa4\x8c""\r\n"
			"                    arrList.selectedLine = this;\r\n"
			"                    arrList.selectedLine.className = \"select\";\r\n"
            "                    selectLine = arrList.name;\r\n"
            "                    selectLineNum = this.id;\r\n"
            // "                    if (arrList.name == \"stopList\") {\r\n"
			// "                       resetScrollPos();\r\n"
			// "                    }\r\n"
			"                    sendSelected(arrList.name, this.id);\r\n" 
			"                };\r\n"
			"            }\r\n"
			"        }\r\n"
			"\r\n"
			"\r\n"
			"        function sendSelected(socId,socData) {\r\n"
			"            var info = { name: \"selected\"+socId, value: socData };\r\n"
			"            var strInfo = JSON.stringify(info);\r\n"
			"            connection.send(strInfo);\r\n"
			"            if (socId == \"stopList\") {\r\n"
			"                resetScrollPos();\r\n"
			"            }\r\n"
			"        }\r\n"
			"\r\n"
			"        function confirmSelected(socId)\r\n"
			"        {\r\n"
            // "            var info = { name: \"confirmed\"+socId, value: 0 };\r\n""
			"            var info = { name: \"confirmed\"+socId, value: selectLineNum };\r\n"
			"            var strInfo = JSON.stringify(info);\r\n"
			"            connection.send(strInfo);\r\n"
			"            if (socId == \"stopList\") {\r\n"
			"                resetScrollPos();\r\n"
			"            }\r\n"
            // "            sendSelected(selectLine, selectLineNum);\r\n"
			"        }\r\n"
			"        function addTableList(id, data) {\r\n"
			"            var tdEl = undefined;\r\n"
			"            var trEl = undefined;\r\n"
			"            var num = 0;\r\n"
			"            var strData = undefined\r\n"
			"            var tableLen = id.getElementsByTagName(\"tr\").length;\r\n"
			"            var dataLen = data.list.length;\r\n"
			"            for (var i = 0; i < dataLen; i++) {\r\n"
			"                tdEl = document.createElement(\"td\");\r\n"
			"                strData = data.list[id.getElementsByTagName(\"tr\").length].id\r\n"
			"                                + \".\"\r\n"
			"                                + data.list[id.getElementsByTagName(\"tr\").length].name;\r\n"
			"                tdEl.appendChild(document.createTextNode(strData));\r\n"
			"                trEl = document.createElement(\"tr\");\r\n"
			"                trEl.id = data.list[id.getElementsByTagName(\"tr\").length].id;\r\n"
			"                trEl.appendChild(tdEl);\r\n"
			"                id.appendChild(trEl);\r\n"
			"            }\r\n"
			"            return num;\r\n"
			"        }\r\n"
			"\r\n"
			"            function deleteTableAllList(id) {\r\n"
			"                var num = id.getElementsByTagName(\"tr\").length;\r\n"
			"                for (var i = 0; i < num; i++) {\r\n"
			"                    id.deleteRow(0);\r\n"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"            function updateJson(destData, srcData) {\r\n"
			"                var tempArr = [];\r\n"
			"                for (var i = 0; i < destData.list.length; i++) {\r\n"
			"                    tempArr[i] = destData.list[i].id;\r\n"
			"                }\r\n"
			"                for (var i = 0; i < srcData.list.length; i++) {\r\n"
			"                    var equlPos = tempArr.indexOf(srcData.list[i].id);\r\n"
			"                    if (equlPos != -1) {\r\n"
			"                        destData.list[equlPos] = srcData.list[i];\r\n"
			"                    }\r\n"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"            function deleteJson(destData, srcData) {\r\n"
			"                var tempArr = [];\r\n"
			"                for (var i = 0; i < destData.list.length; i++) {\r\n"
			"                    tempArr[i] = destData.list[i].id;\r\n"
			"                }\r\n"
			"                for (var i = 0; i < srcData.list.length; i++) {\r\n"
			"                    var equlPos = tempArr.indexOf(srcData.list[i].id);\r\n"
			"                    if (equlPos != -1) {\r\n"
			"                        console.log(\"delete:\" + destData.list[equlPos]);\r\n"
			"                        console.log(\"equlpos\" + equlPos);\r\n"
			"\r\n"
			"                        destData.list.splice(equlPos, 1);\r\n"
			"                    }\r\n"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"            function insertJson(destData, srcData) {\r\n"
			"                var tempArr = [];\r\n"
			"                for (var i = 0; i < destData.list.length; i++) {\r\n"
			"                    tempArr[i] = destData.list[i].id;\r\n"
			"                }\r\n"
			"                for (var i = 0; i < srcData.list.length; i++) {\r\n"
			"                    var equlPos = tempArr.indexOf(srcData.list[i].id);\r\n"
			"                    if (equlPos == -1) {\r\n"
			"                        destData.list = destData.list.concat(srcData.list[i]);\r\n"
			"                    }\r\n"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"\r\n"
			"            function selectJson(selIndex,setID)\r\n"
			"            {\r\n"
			"				 setID=Number(setID);\r\n"
			"                var tempArr = [];\r\n"
			"                for(var i=0; i<arrControl[selIndex].listData.list.length; i++)\r\n"
			"                {\r\n"
			"                    tempArr[i] =arrControl[selIndex].listData.list[i].id;\r\n"
			"                }\r\n"
			"                var equlPos = tempArr.indexOf(setID);\r\n"
			"                console.log(\"equlPos\"+equlPos);\r\n"
			"                if(equlPos != -1)\r\n"
			"                {\r\n"
			"                   moveScroll(arrControl[selIndex].element, equlPos);\r\n"
			"					if (arrControl[selIndex].selectedLine != undefined)\r\n"
			"					{\r\n"
			"						arrControl[selIndex].selectedLine.classList.remove(\"select\");\r\n"
			"						arrControl[selIndex].element.getElementsByTagName(\"tr\")[equlPos].className = \"select\";\r\n"
			"						arrControl[selIndex].selectedLine = arrControl[selIndex].element.getElementsByTagName(\"tr\")[equlPos];\r\n"
			"						arrControl[selIndex].scrollPos = equlPos;\r\n"
			"					}\r\n"
			"					else\r\n"
			"					{\r\n"
			"						arrControl[selIndex].element.getElementsByTagName(\"tr\")[equlPos].classList.add(\"select\");\r\n"
			"						arrControl[selIndex].selectedLine = arrControl[selIndex].element.getElementsByTagName(\"tr\")[equlPos];\r\n"
			"						arrControl[selIndex].scrollPos = equlPos;\r\n"
			"					}"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"\r\n"
			"            function updateAllJson(destData, srcData) {\r\n"
			"                destData.list.splice(0, destData.list.length);\r\n"
			"                insertJson(destData, srcData);\r\n"
			"            }\r\n"
			"\r\n"
			"            function parseJson(srcData) {\r\n"
			"                var destData;\r\n"
			"                var retVal=undefined;\r\n"
			"                if (srcData.hasOwnProperty('list')) {\r\n"
			"                    retVal = arrControl.findIndex(i => i.name == srcData.target);\r\n"
			"                    console.log(srcData.target);\r\n"
			"                    if(retVal!=undefined)\r\n"
			"                    {\r\n"
			"                        if (srcData.type == \"updateall\") {\r\n"
			"                            console.log(\"updateall\");\r\n"
			"                            updateAllJson(arrControl[retVal].listData, srcData);\r\n"
			"                        }\r\n"
			"                        else if (srcData.type == \"update\") { \r\n"
			"                            console.log(\"update\");\r\n"
			"                            updateJson(arrControl[retVal].listData, srcData);\r\n"
			"                        }\r\n"
			"                        else if (srcData.type == \"delete\") {\r\n"
			"                            console.log(\"delete\");\r\n"
			"                            deleteJson(arrControl[retVal].listData, srcData);\r\n"
			"                        }\r\n"
			"                        else if (srcData.type == \"insert\") {\r\n"
			"                            console.log(\"insert\");\r\n"
			"                            insertJson(arrControl[retVal].listData, srcData);\r\n"
			"                        }\r\n"
			"                        else {\r\n"
			"                            retVal = -1;\r\n"
			"                        }\r\n"
			"                    }\r\n"
			"                }\r\n"
			"                else\r\n"
			"                {\r\n"
			"                    for (var i = 0; i < srcData.length; i++) {\r\n"
			"                        var temp,selTable;\r\n"
			"                        var ctrlType = srcData[i].name.substr(0, 3);\r\n"
			"                        switch(ctrlType){\r\n"
			"                            case \"txt\":\r\n"
			"                                temp = document.getElementById(srcData[i].name);\r\n"
			"                                temp.innerText = srcData[i].value;\r\n"
			"                                break;\r\n"
			"                            case \"ind\":\r\n"
			"                                temp = document.getElementById(srcData[i].name);\r\n"
			"                                temp.style = srcData[i].value;\r\n"
			"                                break;\r\n"
			"                            case \"grp\":\r\n"
			"                                break;\r\n"
			"                            case \"val\":\r\n"
			"                                eval(srcData[i].value);\r\n"
			"                                break;\r\n"
			"                            case \"slt\":\r\n"
			"                                temp=srcData[i].name.substr(3,srcData[i].length);\r\n"
			"                                selTable=arrControl.findIndex(i => i.name == temp);\r\n"
			"                                if(selTable!=undefined)\r\n"
			"                                {\r\n"
			"                                    selectJson(selTable,srcData[i].value);\r\n"
			"									 sendSelected(temp, srcData[i].value);\r\n"
			"                                }\r\n"
			"                            default:\r\n"
			"                                break;\r\n"
			"                        } \r\n"
			"                    }\r\n"
			"                    retVal = -1;\r\n"
			"                }\r\n"
			"                return retVal;\r\n"
			"            }\r\n"
			"\r\n"
			"            function uploadTable(tableToUpload,arrIndex,socData)\r\n"
			"            {\r\n"
			"                deleteTableAllList(tableToUpload);\r\n"
			"                addTableList(tableToUpload, socData);\r\n"
			"                arrControl[arrIndex].listData = socData;\r\n"
			"                scanList(arrControl[arrIndex]);\r\n"
			"            }\r\n"
			"\r\n"
			"            function resetScrollPos()\r\n"
			"            {\r\n"
			"               \r\n"
			"                var index = arrControl.findIndex(i => i.name == \"routeList\");\r\n"
			"                console.log(index);\r\n"
			"                arrControl[index].scrollPos = 0;\r\n"
			"            }\r\n"
			"\r\n"
			"            function load() {\r\n"
			"                var wsproto = (location.protocol === 'https:') ? 'wss:' : 'ws:';\r\n"
			"                connection = new WebSocket(wsproto + '//' + window.location.host + '/wsDestination');\r\n"
			"                connection.onmessage = function (e) {\r\n"
			"                    var parseData = JSON.parse(e.data);\r\n"
			"                    var rV = parseJson(parseData);\r\n"
			"                    if(rV!=-1)\r\n"
			"                    {\r\n"
			"                        console.log(rV);\r\n"
			"                        console.log(parseData);\r\n"
			"                        uploadTable(arrControl[rV].element,rV,parseData);\r\n"
			"                    }\r\n"
			"                }\r\n"
			"                connection.onerror = function (error) {\r\n"
			"                    alert('WebSocket error');\r\n"
			"                    connection.close();\r\n"
			"                }\r\n"
			"            }\r\n"
			"\r\n"
			"            function moveScroll(id, index) {\r\n"
			"                console.log(id);\r\n"
			"                console.log(index);\r\n"
			"                var tableTr = id.getElementsByTagName(\"tr\")[index];\r\n"
			"                var scrollTo = tableTr.offsetTop;\r\n"
			"                id.scrollTop = scrollTo;\r\n"
			"            }\r\n"
			"\r\n"
			"\r\n"
			"            function clickLineUpDn(btn, id) {\r\n"
			"                var index = arrControl.findIndex(i => i.name == id.id);\r\n"
			"                var addNum = 0;\r\n"
			"                if (btn == 'up') {\r\n"
			"                    if (arrControl[index].scrollPos == 0) {\r\n"
			"\r\n"
			"                    }\r\n"
			"                    else {\r\n"
			"                      \r\n"
			"                        if (arrControl[index].scrollPos >= cTABLE_LIST_NUM) {\r\n"
			"                            arrControl[index].scrollPos -= cTABLE_LIST_NUM;\r\n"
			"\r\n"
			"                        }\r\n"
			"                   \r\n"
			"                        else {\r\n"
			"                            arrControl[index].scrollPos = 0;\r\n"
			"                        }\r\n"
			"                        moveScroll(id, arrControl[index].scrollPos);\r\n"
			"                    }\r\n"
			"                }\r\n"
			"                else {\r\n"
			"                    console.log(arrControl[index].scrollPos);\r\n"
			"                    console.log(id.getElementsByTagName(\"tr\").length);\r\n"
			"                    if (arrControl[index].scrollPos >= (id.getElementsByTagName(\"tr\").length - cTABLE_LIST_NUM)) {\r\n"
			"                        scanList(arrControl[index]);\r\n"
			"                        addNum = addTableList(id, arrControl[index].listData);\r\n"
			"                        scanList(arrControl[index]);\r\n"
			"                        //console.log(addNum);\r\n"
			"                      \r\n"
			"\r\n"
			"                \r\n"
			"                        arrControl[index].scrollPos += addNum;\r\n"
			"                    }\r\n"
			"                    else {\r\n"
			"                        arrControl[index].scrollPos += cTABLE_LIST_NUM;\r\n"
			"                    }\r\n"
			"                    moveScroll(id, arrControl[index].scrollPos);\r\n"
			"\r\n"
			"                }\r\n"
			"            }\r\n"
			"    </script>\r\n"
			"</body>\r\n"
			"\r\n"
			"</html>\r\n"
		);
		return true;
	}
};

/*
"        function load() {\r\n"
"            var wsproto = (location.protocol === 'https:') ? 'wss:' : 'ws:';\r\n"
"            connection = new WebSocket(wsproto + '//' + window.location.host + '/wsIndex');\r\n"
"            connection.onmessage = function (e) {\r\n"
"                console.log(e.data);\r\n"
"                var parseData = JSON.parse(e.data);\r\n"
"                for(var i=0;i<parseData.length;i++)\r\n"
"                {\r\n"
"                    var temp = document.getElementById(parseData[i].name);\r\n"
"                    temp.innerText = parseData[i].value;\r\n"
"                }\r\n"
"            }\r\n"
"            connection.onerror = function (error) {\r\n"
"                alert('WebSocket error');\r\n"
"                connection.close();\r\n"
"            }\r\n"
"        }\r\n"
*/
