#include "GetCSSPages.h"



GetCSSPages::GetCSSPages()
{
}


GetCSSPages::~GetCSSPages()
{
}


const char* GetCSSPages::pControlType =
	"section{\r\n"
	"    display:                        inline-block;\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#txtControl{ /* \xec\x9e\x90\xeb\x8f\x99""/\xec\x88\x98\xeb\x8f\x99"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    background:                     rgb(8, 8, 156); \r\n"
	"    border:                         solid rgb(8, 8, 156); \r\n"
	"    border-radius:                  20px;\r\n"
	"    width:                          300px;\r\n"
	"    height:                         200px;\r\n"
	"    /* margin:                         auto; */\r\n"
	"    margin:                         70px 250px;\r\n"
	"    /* padding-top:                    40px; */\r\n"
	"    font-size:                      80px;\r\n"
	"    font-weight:                    700;\r\n"
	"    color:                          white;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#cancBtn{\r\n"
	"    margin-right:                   40px;          \r\n"
	"}\r\n"
	"\r\n"
	"#okBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n";


const char *GetCSSPages::pDestination =
	"section{\r\n"
	"    /* display:                        block; */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#txtLine{ /* \xed\x96\x89\xec\x84\xa0""(\xec\x83\x81\xed\x96\x89\xec\x84\xa0""/\xed\x95\x98\xed\x96\x89\xec\x84\xa0"") \xec\x84\xa0\xed\x83\x9d\xed\x95\x98\xeb\x8a\x94"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    background:                     rgb(68, 114, 196);\r\n"
	"    /* border:                         none; */\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          150px;\r\n"
	"    height:                         50px;\r\n"
	"    margin:                         10px 0px 15px 25px;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    800;\r\n"
	"    \r\n"
	"    color:                          white;\r\n"
	"}\r\n"
	"\r\n"
	".inforTable{ /* \xeb\x85\xb8\xec\x84\xa0\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xeb\xb0\x8f"" \xeb\xb0\xa9\xec\x86\xa1\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    background-color:               white;\r\n"
	"    border:                         solid thin navy;\r\n"
	"    border-collapse:                collapse;\r\n"
	"    overflow-y:                     hidden; /* \xec\x8a\xa4\xed\x81\xac\xeb\xa1\xa4"" \xec\x88\xa8\xea\xb8\xb0\xea\xb8\xb0"" */\r\n"
	"    width:                          280px;\r\n"
	"    height:                         250px;\r\n"
	"    /* font-size:                      20px; */\r\n"
	"    /* margin:                         5px; */\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	".inforTable tr:nth-child(2n){ /* \xeb\x85\xb8\xec\x84\xa0\xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"", \xeb\xb0\xa9\xec\x86\xa1\xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94\xec\x9d\x98"" 2n\xeb\xb2\x88\xec\xa7\xb8"" tr */\r\n"
	"    border-top:                     dotted thin; /* \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94\xec\x9d\x98"" \xeb\x8f\x84\xed\x8a\xb8"" \xed\x91\x9c\xec\x8b\x9c"" */\r\n"
	"    border-bottom:                  dotted thin;\r\n"
	"}\r\n"
	"\r\n"
	".inforTable td{\r\n"
	"    width:                          280px;\r\n"
	"    height:                         50px;\r\n"
	"    \r\n"
	"    padding:                        5px 10px;\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	"#stopList{ /* \xeb\x85\xb8\xec\x84\xa0"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    margin-left:                    25px;\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"#paTable{ /* \xeb\xb0\xa9\xec\x86\xa1"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    margin-left:                    10px;\r\n"
	"}\r\n"
	"\r\n"
	".select{\r\n"
	"    background:                     rgba(72, 130, 255, 0.2);\r\n"
	"    /* height:50px; */\r\n"
	"    /* display: block; */\r\n"
	"  \r\n"
	"}\r\n"
	"\r\n"
	"/* .select td{\r\n"
	"    margin:0;\r\n"
	"    position: absolute;\r\n"
	"    animation-name:marquee;\r\n"
	"    animation-timing-function:linear;\r\n"
	"    animation-duration:5s;\r\n"
	"    animation-iteration-count:infinite;\r\n"
	"}\r\n"
	"\r\n"
	"@keyframes marquee {\r\n"
	"    from   { transform: translate(0%%);}\r\n"
	"    to { transform: translate(100%%);}\r\n"
	"} */\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	".arrowBtn{ /* Up/Dwon \xed\x99\x94\xec\x82\xb4\xed\x91\x9c"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    \r\n"
	"    /* border-spacing:                 0px 50px 0px; */\r\n"
	"    height:                         250px;\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn td{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    margin-bottom:                  20px;\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn button{ \r\n"
	"    width:                          70px;\r\n"
	"    height:                         70px\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#cancBtn{\r\n"
	"    margin-right:                   40px;          \r\n"
	"}\r\n"
	"\r\n"
	"#okBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n";

	const char *GetCSSPages::pDetailDiag =
		"section{\r\n"
		"    width:                          796px;\r\n"
		"    height:                         336px;\r\n"
		"}\r\n"
		"\r\n"
		"#stat{\r\n"
		"    margin-top:                     15px;\r\n"
		"    margin-bottom:                  15px;\r\n"
		"}\r\n"
		"\r\n"
		"#stat p{\r\n"
		"    border:                         solid thin navy;\r\n"
		"    margin:                         0px 10px 5px 670px;\r\n"
		"    width:                          60px;\r\n"
		"    text-align:                     center;\r\n"
		"    color:                          white;\r\n"
		"}\r\n"
		"\r\n"
		"#detailDiag{\r\n"
		"    border:                         solid 1px navy;\r\n"
		"    border-radius:                  25px;\r\n"
		"    width:                          700px;\r\n"
		"    height:                         240px;\r\n"
		"    margin:                         0px 50px;\r\n"
		"}\r\n"
		"\r\n"
		".sideDevice{ /* \xec\x96\x91"" \xec\x82\xac\xec\x9d\xb4\xeb\x93\x9c"" IDD \xeb\xb6\x80\xeb\xb6\x84"" */\r\n"
		"    width:                          700px;\r\n"
		"    height:                         60px;\r\n"
		"    text-align:                     center;\r\n"
		"    \r\n"
		"}\r\n"
		"\r\n"
		".sideDevice p{ /* IDD\xec\x9d\x98"" P\xec\x9a\x94\xec\x86\x8c"" */\r\n"
		"    float:                          left;\r\n"
		"    border:                         solid thin;\r\n"
		"    width:                          100px;\r\n"
		"    height:                         30px;\r\n"
		"    margin-top:                     10px;\r\n"
		"    padding-top:                    2px;\r\n"
		"}\r\n"
		"\r\n"
		".leftIdd1{ /* \xec\x99\xbc\xec\xaa\xbd"" IDD1 */\r\n"
		"    margin-left:                    135px;\r\n"
		"}\r\n"
		"\r\n"
		".leftIdd2{ /* \xec\x99\xbc\xec\xaa\xbd"" IDD2 */\r\n"
		"    margin-right:                   40px;\r\n"
		"}\r\n"
		"\r\n"
		".centerDevice{ /* \xec\x84\xbc\xed\x84\xb0"" div\xec\x97\x90"" FTNDD, 1\xed\x98\xb8\xec\xb0\xa8"", PII \xeb\xb6\x80\xeb\xb6\x84"" */\r\n"
		"    width:                          700px;\r\n"
		"    height:                         120px;\r\n"
		"    text-align:                     center;\r\n"
		"}\r\n"
		"\r\n"
		".centerDevice p, .centerDevice span{ /* \xec\x84\xbc\xed\x84\xb0"" div\xec\x97\x90"" FTNDD, 1\xed\x98\xb8\xec\xb0\xa8"", PII \xeb\xb6\x80\xeb\xb6\x84"" */\r\n"
		"    border:                         solid thin navy;\r\n"
		"    float:                          left;\r\n"
		"    color:                          white;\r\n"
		"    font-size:                      20px;\r\n"
		"    font-weight:                    600; \r\n"
		"}\r\n"
		"\r\n"
		".centerDevice .frontDev{ /* FTNDD \xec\x9e\xa5\xec\xb9\x98"" */\r\n"
		"    width:                          100px;\r\n"
		"    height:                         120px;\r\n"
		"    margin-left:                    25px;\r\n"
		"    margin-right:                   90px;\r\n"
		"    padding-top:                    40px;\r\n"
		"}\r\n"
		"\r\n"
		".centerDevice #carNum{ /* X\xed\x98\xb8\xec\xb0\xa8"" */\r\n"
		"    background:                     rgb(6, 18, 182);\r\n"
		"    width:                          120px;\r\n"
		"    height:                         50px;\r\n"
		"    margin:                         35px 10px 0px 10px;\r\n"
		"    margin-top:                     35px;\r\n"
		"    padding-top:                    8px;\r\n"
		"}\r\n"
		"\r\n"
		".centerDevice .rearDev{ /* PII \xec\x9e\xa5\xec\xb9\x98"" */\r\n"
		"    width:                          90px;\r\n"
		"    height:                         120px;\r\n"
		"    margin-left:                    90px;\r\n"
		"    padding-top:                    40px;\r\n"
		"}\r\n"
		"\r\n"
		".arrowImg{ /* << >> \xed\x99\x94\xec\x82\xb4\xed\x91\x9c"" */\r\n"
		"    float:                          left;\r\n"
		"    width:                          70px;\r\n"
		"    margin-top:                     25px;\r\n"
		"}\r\n"
		"\r\n"
		"#prevBtn{\r\n"
		"    margin-right:                   45px;          \r\n"
		"}\r\n";


const char *GetCSSPages::pDiagnosis =
	"/* -- section -------------------------------- */\r\n"
	"section{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#stat{ /* OK, NG Div */\r\n"
	"    margin-top:                     15px;\r\n"
	"    margin-bottom:                  15px;\r\n"
	"}\r\n"
	"\r\n"
	"#stat p{ /* OK, NG \xea\xb0\x81\xea\xb0\x81"" \xec\x9a\x94\xec\x86\x8c"" */\r\n"
	"    border:                         solid thin black;\r\n"
	"    margin:                         0px 20px 5px 670px;\r\n"
	"    width:                          60px;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          white;\r\n"
	"}\r\n"
	"\r\n"
	".carNumber{ /* 0\xed\x98\xb8\xec\xb0\xa8""~7\xed\x98\xb8\xec\xb0\xa8"" \xec\x98\x81\xec\x97\xad"" */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         140px;\r\n"
	"    margin:                         10px 0px;\r\n"
	"    padding:                        0px 20px 0px 60px;\r\n"
	"}\r\n"
	"\r\n"
	".carNumber button{ /* 0\xed\x98\xb8\xec\xb0\xa8""~7\xed\x98\xb8\xec\xb0\xa8"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    /* background-color:               rgb(0, 185, 25); \xec\x83\x81\xed\x83\x9c\xec\x97\x90"" \xeb\x94\xb0\xeb\x9d\xbc"" \xeb\xb3\x80\xea\xb2\xbd\xed\x95\xb4\xec\x95\xbc\xed\x95\xa8"" */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          130px;\r\n"
	"    height:                         60px;\r\n"
	"    color:                          white;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    500;\r\n"
	"    text-align:                     center;\r\n"
	"    margin-right:                   45px;         \r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#prevBtn{\r\n"
	"    margin-right:                   45px;          \r\n"
	"}\r\n";


const char *GetCSSPages::pFormNumber =
	"section{\r\n"
	"    /* position:                       absolute; */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#border{ /* section \xec\x95\x88\xec\x97\x90"" \xed\x95\x98\xec\x96\x80\xec\x83\x89"" \xed\x85\x8c\xeb\x91\x90\xeb\xa6\xac"" */\r\n"
	"    border:                         solid 5px white;\r\n"
	"    border-radius:                  20px;\r\n"
	"    margin:                         22px 40px 0px 40px;\r\n"
	"    width:                          700px;\r\n"
	"    height:                         300px;\r\n"
	"}\r\n"
	"\r\n"
	".area{ /* \xed\x95\x98\xec\x96\x80"" \xed\x85\x8c\xeb\x91\x90\xeb\xa6\xac"" \xec\x95\x88\xec\x97\x90"" '\xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8\xed\x91\x9c\xec\x8b\x9c\xec\x98\x81\xec\x97\xad""'\xea\xb3\xbc"" '\xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c\xec\x98\x81\xec\x97\xad""'\xec\x9c\xbc\xeb\xa1\x9c"" \xec\x98\x81\xec\x97\xad\xec\x9d\x84"" \xeb\x82\x98\xeb\x88\x88\xeb\x8b\xa4"" */\r\n"
	"    float:                          left;\r\n"
	"    width:                          340px;\r\n"
	"    height:                         280px;\r\n"
	"                       \r\n"
	"}\r\n"
	"\r\n"
	"#txtFormNum{ /* \xed\x8e\xb8\xec\x84\xb1\xeb\xb2\x88\xed\x98\xb8"" */\r\n"
	"    background-color:             white;\r\n"
	"    border:                         solid thin navy;\r\n"
	"    width:                          250px;\r\n"
	"    height:                         80px;\r\n"
	"    margin:                         30px 35px;\r\n"
	"    font-size:                      60px;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	".area table{ /* \xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c"" */\r\n"
	"    border-spacing:                 8px;\r\n"
	"    margin:                         20px 10px;\r\n"
	"}\r\n"
	".area table td{ /* \xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c\xec\x9d\x98"" \xec\x88\xab\xec\x9e\x90\xed\x82\xa4\xeb\x93\xa4"" */\r\n"
	"    border:                         solid thin navy;\r\n"
	"    background:                     rgb(163, 162, 162);\r\n"
	"    width:                          150px;\r\n"
	"    height:                         50px;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          white;\r\n"
	"    font-size:                      20px;\r\n"
	"    font-weight:                    500;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#cancBtn{\r\n"
	"    margin-right:                   40px;          \r\n"
	"}\r\n"
	"\r\n"
	"#okBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n";

const char *GetCSSPages::pIndex =
	"aside{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          320px;\r\n"
	"    height:                         340px;\r\n"
	"    float:                          right;\r\n"
	"}\r\n"
	"\r\n"
	"#version{ /* \xeb\xb2\x84\xec\xa0\x84"" \xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    font-size:                      20px;\r\n"
	"    float:                          right;\r\n"
	"    margin:                         0px 45px 5px 0px;\r\n"
	"    /* margin-right:                   45px; */\r\n"
	"}\r\n"
	"\r\n"
	"#statusTable{ /* \xea\xb0\x81"" \xec\x83\x81\xed\x83\x9c\xec\x97\x90"" \xeb\x8c\x80\xed\x95\x9c"" \xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    border:                         solid 2px white;\r\n"
	"    border-radius:                  30px;\r\n"
	"    border-spacing:                 0px;\r\n"
	"    width:                          260px;\r\n"
	"    height:                         280px;\r\n"
	"    background:                     gray;\r\n"
	"    margin:                         auto;\r\n"
	"    /* margin-top:                     40px; */\r\n"
	"    \r\n"
	"    padding:                        10px;\r\n"
	"}\r\n"
	"\r\n"
	"#statusTable tr td{\r\n"
	"    font-size:                      22px;\r\n"
	"    font-weight:                    bold;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          white;\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"#statusTable td:nth-child(2n+1){ \r\n"
	"    border-right:                    solid thin; /* \xec\x98\xa4\xeb\xa5\xb8\xec\xaa\xbd\xec\x97\x90"" \xed\x85\x8c\xeb\x91\x90\xeb\xa6\xac"" */\r\n"
	"}\r\n"
	"\r\n"
	"/* -- section ---------------------------------------- */\r\n"
	"section{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          480px;\r\n"
	"    height:                         340px;\r\n"
	"\r\n"
	"    padding:                        25px;\r\n"
	"}\r\n"
	"\r\n"
	".sectionTitle{ /* '\xed\x96\x89\xec\x84\xa0""', '\xec\xa2\x85\xec\xb0\xa9\xec\x97\xad""', '\xec\x9d\xb4\xeb\xb2\x88\xec\x97\xad""' */\r\n"
	"    font:                           22px bolder;\r\n"
	"    font-weight:                    1000;\r\n"
	"}\r\n"
	"\r\n"
	".sectionValue{ /* \xed\x96\x89\xec\x84\xa0\xec\xa0\x95\xeb\xb3\xb4"", \xec\xa2\x85\xec\xb0\xa9\xec\x97\xad\xec\xa0\x95\xeb\xb3\xb4"", \xec\x9d\xb4\xeb\xb2\x88\xec\x97\xad\xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    border:                         outset;\r\n"
	"    box-shadow:                     1px 1px 1px 1px rgb(212, 212, 212);\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          420px;\r\n"
	"    background-color:               rgb(214, 214, 214);\r\n"
	"    margin:                         5px 0px 20px 0px;\r\n"
	"    text-align:                     center;    \r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"#txtLineType{ /* \xed\x96\x89\xec\x84\xa0\xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    height:                         45px;\r\n"
	"    padding-top:                    5px;\r\n"
	"    font-size:                      25px;\r\n"
	"}\r\n"
	"#txtDestination{ /* \xec\xa2\x85\xec\xb0\xa9\xec\x97\xad\xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    height:                         45px;\r\n"
	"    padding-top:                    5px;\r\n"
	"    font-size:                      25px;\r\n"
	"}\r\n"
	"\r\n"
	"#txtNextStation{ /* \xec\x9d\xb4\xeb\xb2\x88\xec\x97\xad\xec\xa0\x95\xeb\xb3\xb4"" */\r\n"
	"    background-color:               rgb(255, 217, 100);\r\n"
	"    height:                         75px;\r\n"
	"    padding-top:                    15px;\r\n"
	"    font-size:                      30px;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#menuBtn{\r\n"
	"    float:                          right;\r\n"
	"    margin-right:                   45px;       \r\n"
	"    \r\n"
	"    width:                          160px; \r\n"
	"}\r\n";

const char *GetCSSPages::pMenu =
	"section{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"div .menu{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    padding:                        50px 55px 25px 28px;\r\n"
	"}\r\n"
	"\r\n"
	".menu button{\r\n"
	"    display:                        inline-block;\r\n"
	"    background-color:               white;\r\n"
	"    border:                         solid 1px navy;\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          150px;\r\n"
	"    height:                         80px;\r\n"
	"    margin-left:                    25px;\r\n"
	"    /* padding-top:                    25px; */\r\n"
	"    font-size:                      20px;\r\n"
	"    font-weight:                    550;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	".menu button:hover{\r\n"
	"    box-shadow:                     200px 0 0 0 rgb(6, 6, 122) inset;\r\n"
	"    color:                          white;\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#prevBtn{\r\n"
	"    margin-right:                   45px;          \r\n"
	"}\r\n";

const char *GetCSSPages::pPISC=
	"html{overflow:hidden;}\r\n"
	"*{\r\n"
	"    box-sizing:                     border-box;\r\n"
	"    margin:                         0px;\r\n"
	"    font-family:                    \"Nanum Gothic\";\r\n"
	"}\r\n"
	"\r\n"
	"body{\r\n"
	"    margin:                         auto; /* \xec\xa0\xa4\xeb\xa1\x9c"" */\r\n"
	"}\r\n"
	"\r\n"
	"a{\r\n"
	"    text-decoration:                none;\r\n"
	"    color:                          black;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- LCD Resolution: 800 x 3(RGB) x 480 ------------- */\r\n"
	"#container{\r\n"
	"    background-color:               #eeeeee;\r\n"
	"    width:                          800px;\r\n"
	"    height:                         480px;    \r\n"
	"}\r\n"
	"\r\n"
	":focus{\r\n"
	"    outline:                        none;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- header ----------------------------------------- */\r\n"
	"header{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         80px;\r\n"
	"    position:                       absolute;\r\n"
	"    top:                            0px;\r\n"
	"    padding:                        10px 10px 0px 10px;\r\n"
	"}\r\n"
	"\r\n"
	"#logo{ /* \xec\x84\x9c\xec\x9a\xb8\xea\xb5\x90\xed\x86\xb5\xea\xb3\xb5\xec\x82\xac"" \xeb\xa1\x9c\xea\xb3\xa0"" */\r\n"
	"    width:                          180px;\r\n"
	"    height:                         50px;\r\n"
	"    float:                          left;\r\n"
	"    margin-bottom:                  5px;\r\n"
	"}\r\n"
	"\r\n"
	"#headerTitle{ /* Header\xec\x9d\x98"" \xed\x83\x80\xec\x9d\xb4\xed\x8b\x80"" */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          400px;;\r\n"
	"    height:                         50px;\r\n"
	"    float:                          right;\r\n"
	"    padding-top:                    5px;\r\n"
	"    text-align:                     center;\r\n"
	"    font-size:                      30px;\r\n"
	"    font-weight:                    bold;\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"#nowTime{ /* \xed\x98\x84\xec\x9e\xac\xec\x8b\x9c\xea\xb0\x84"" */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          180px;\r\n"
	"    height:                         50px;\r\n"
	"    float:                          right;\r\n"
	"    padding-left:                   20px;\r\n"
	"    text-align:                     center;\r\n"
	"    font-size:                      18px;\r\n"
	"    font-weight:                    bold;\r\n"
	"}\r\n"
	"\r\n"
	"#headerLine{ /* \xed\x97\xa4\xeb\x8d\x94\xec\x99\x80"" \xec\x84\xb9\xec\x85\x98"" \xec\x82\xac\xec\x9d\xb4\xec\x9d\x98"" \xeb\x84\xa4\xec\x9d\xb4\xeb\xb9\x84\xec\x83\x89"" \xeb\xb0\x91\xec\xa4\x84"" */\r\n"
	"    width:                          780px;\r\n"
	"    height:                         10px;\r\n"
	"    background:                   rgb(47, 85, 150);\r\n"
	"    border:                         0px;\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"/* -- section ---------------------------------------- */\r\n"
	"section{\r\n"
	"    position:                       absolute;\r\n"
	"    top:                            80px;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- aside ------------------------------------------ */\r\n"
	"aside{\r\n"
	"    position:                       absolute;\r\n"
	"    top:                            80px;\r\n"
	"    left:                          480px;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ----------------------------------------- */\r\n"
	"footer{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         65px;\r\n"
	"    position:                       absolute;\r\n"
	"    top:                            420px;\r\n"
	"}\r\n"
	"\r\n"
	".roundFootBtn{ /* Footer\xec\x97\x90"" \xec\x9d\xb4\xec\xa0\x84"", \xec\x8b\x9c\xec\x9e\x91"", \xec\xa0\x95\xec\xa7\x80""... \xec\x97\x90"" \xec\x93\xb0\xec\x9d\xb4\xeb\x8a\x94"" \xeb\x91\xa5\xea\xb7\xbc"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    border:                         outset;\r\n"
	"    border-top:                     solid rgb(205, 205, 205);\r\n"
	"    border-left:                    solid rgb(205, 205, 205);\r\n"
	"    /* box-shadow:                     1px 1px 1px 1px rgb(182, 182, 182); */\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          140px;\r\n"
	"    height:                         45px;\r\n"
	"    background-color:               rgb(235, 235, 235);\r\n"
	"    float:                          right;\r\n"
	"    /* margin-right:                   45px; */\r\n"
	"    padding:                        3px;\r\n"
	"    font-size:                      25px;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	"/* .roundFootBtn:hover{\r\n"
	"    box-shadow: 200px 0 0 0 rgba(192, 192, 192, 0.5) inset;\r\n"
	"} */\r\n"
	"\r\n"
	"\r\n"
	".rectFootBtn{ /* Footer\xec\x97\x90"" \xed\x99\x95\xec\x9d\xb8"", \xec\x9d\xb4\xec\xa0\x84""...\xec\x97\x90"" \xec\x93\xb0\xec\x9d\xb4\xeb\x8a\x94"" \xeb\x84\xa4\xeb\xaa\xa8"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    border:                         outset;\r\n"
	"    border-top:                     solid rgb(205, 205, 205);\r\n"
	"    border-left:                    solid rgb(205, 205, 205);\r\n"
	"    width:                          120px;\r\n"
	"    height:                         45px;\r\n"
	"    background-color:               rgb(235, 235, 235);\r\n"
	"    float:                          right;\r\n"
	"    /* margin-right:                   30px; */\r\n"
	"    padding:                        3px;\r\n"
	"    font-size:                      25px;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	".roundFootBtn:active, .rectFootBtn:active{\r\n"
	"    background-color:               rgb(172, 172, 172);\r\n"
	"    color:                          white;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- etc --------------------------------------- */\r\n"
	".ngColor{ /* NG\xeb\xa5\xbc"" \xeb\x82\x98\xed\x83\x80\xeb\x82\xb4\xeb\x8a\x94"" RED */\r\n"
	"    background-color:               red;\r\n"
	"}\r\n"
	"\r\n"
	".okColor{ /* OK\xeb\xa5\xbc"" \xeb\x82\x98\xed\x83\x80\xeb\x82\xb4\xeb\x8a\x94"" GREEN */\r\n"
	"    background-color:               rgb(0, 185, 25);\r\n"
	"    \r\n"
	"}\r\n\r\n";

const char *GetCSSPages::pPowerSaving =
	"section{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#stat{ /* \xec\xa0\x88\xec\xa0\x84\xeb\xaa\xa8\xeb\x93\x9c"", \xec\x9d\xbc\xeb\xb0\x98\xeb\xaa\xa8\xeb\x93\x9c"" Div */\r\n"
	"    margin:                         15px 50px 15px 0px;\r\n"
	"    /* margin-top:                     15px;\r\n"
	"    margin-bottom:                  15px; */\r\n"
	"}\r\n"
	"#stat button{ /* \xec\xa0\x88\xec\xa0\x84\xeb\xaa\xa8\xeb\x93\x9c"", \xec\x9d\xbc\xeb\xb0\x98\xeb\xaa\xa8\xeb\x93\x9c"" \xea\xb0\x81\xea\xb0\x81"" \xec\x9a\x94\xec\x86\x8c"" */\r\n"
	"    /* border:                         outset; */\r\n"
	"    border-radius:                  10px;\r\n"
	"    float:                          right;\r\n"
	"    \r\n"
	"    width:                          130px;\r\n"
	"    height:                         50px;\r\n"
	"    margin:                         0px 20px 5px 0px;\r\n"
	"    padding:                        5px;    \r\n"
	"    \r\n"
	"    font-size:                      20px;\r\n"
	"    font-weight:                    600;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	".powerSaving{ /* \xec\xa0\x88\xec\xa0\x84\xeb\xaa\xa8\xeb\x93\x9c"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    background-color:               rgb(45, 85, 150);\r\n"
	"    color:                          white;\r\n"
	"    box-shadow:                     0px 1px 2px rgb(45, 85, 150);\r\n"
	"}\r\n"
	"\r\n"
	".powerNormal{ /* \xec\xa0\x88\xec\xa0\x84\xed\x95\xb4\xec\xa0\x9c"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    background-color:               rgba(5, 95, 255, 0.1);\r\n"
	"    color:                          black;\r\n"
	"    box-shadow:                     0px 1px 1px rgba(5, 95, 255, 0.1);\r\n"
	"}\r\n"
	"\r\n"
	".carNumber{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         140px;\r\n"
	"    margin:                         10px 0px;\r\n"
	"    padding:                        0px 20px 0px 60px;\r\n"
	"}\r\n"
	"\r\n"
	".carNumber button{\r\n"
	"    display:                        inline-block;\r\n"
	"    /* background-color:               rgb(0, 185, 25); \xec\x83\x81\xed\x83\x9c\xec\x97\x90"" \xeb\x94\xb0\xeb\x9d\xbc"" \xeb\xb3\x80\xea\xb2\xbd\xed\x95\xb4\xec\x95\xbc\xed\x95\xa8"" */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          130px;\r\n"
	"    height:                         60px;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    500;\r\n"
	"    text-align:                     center;\r\n"
	"    margin-right:                   45px;         \r\n"
	"}\r\n"
	"#prevBtn{\r\n"
	"    margin-right:                   45px;          \r\n"
	"}\r\n";

const char *GetCSSPages::pManualOperation =
	" *\r\n"
	" * File : selfDriving.css\r\n"
	" * Author : WJIS KEJ\r\n"
	" * PJ Description : \xec\x84\x9c\xec\x9a\xb8\xea\xb5\x90\xed\x86\xb5\xea\xb3\xb5\xec\x82\xac"" 336\xec\xb9\xb8"" \xed\x99\x94\xeb\xa9\xb4\xec\x84\xa4\xec\xa0\x95\xea\xb8\xb0""(PISC) HTML\xec\x9d\x98"" CSS(Style) \r\n"
	" * File Description : \xec\x88\x98\xeb\x8f\x99\xec\x9a\xb4\xed\x96\x89"" \xed\x99\x94\xeb\xa9\xb4\xec\x9d\x98"" \xec\x8a\xa4\xed\x83\x80\xec\x9d\xbc\xec\x8b\x9c\xed\x8a\xb8""\r\n"
	" * Date : 2020.02.17 ~\r\n"
	" *\r\n"
	" * --------------------------------------------------------------------- */\r\n"
	"\r\n"
	"/* -- section ---------------------------------------- */\r\n"
	"section{\r\n"
	"    /* display:                        block; */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- section : area1(\xec\x99\xbc\xec\xaa\xbd"") ------------- */\r\n"
	"#area1{\r\n"
	"    display:                        inline-block;\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          550px;       \r\n"
	"    height:                         340px;          \r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	"#txtLine{ /* \xed\x96\x89\xec\x84\xa0""(\xec\x83\x81\xed\x96\x89\xec\x84\xa0""/\xed\x95\x98\xed\x96\x89\xec\x84\xa0"") */\r\n"
	"    display:                        inline-block;\r\n"
	"    border:                         thin solid rgb(0, 0, 145);\r\n"
	"    background:                     rgba(0, 0, 255, 0.1);\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          150px;\r\n"
	"    height:                         50px;\r\n"
	"    margin:                         20px 0px 20px 35px;\r\n"
	"    padding:                        7px;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    800;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          rgb(25, 25, 210);\r\n"
	"}\r\n"
	"\r\n"
	"#txtDestination{ /* \xed\x96\x89\xec\x84\xa0""(\xec\x83\x81\xed\x96\x89\xec\x84\xa0""/\xed\x95\x98\xed\x96\x89\xec\x84\xa0"") */\r\n"
	"    display:                        inline-block;\r\n"
	"    border:                         thin solid navy;\r\n"
	"    background:                     rgba(0, 0, 255, 0.1);\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          250px;\r\n"
	"    height:                         50px;\r\n"
	"    margin:                         15px 0px;\r\n"
	"    padding:                        7px;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    800;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          rgb(25, 25, 210);\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"#paTable{ /* \xeb\xb0\xa9\xec\x86\xa1\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    background-color:               white;\r\n"
	"    border:                         solid thin navy;\r\n"
	"    border-collapse:                collapse;\r\n"
	"    /* border-spacing:                 0px; */\r\n"
	"    overflow-y:                     hidden; /* \xec\x8a\xa4\xed\x81\xac\xeb\xa1\xa4"" \xec\x88\xa8\xea\xb8\xb0\xea\xb8\xb0"" */\r\n"
	"    width:                          400px;\r\n"
	"    height:                         250px;\r\n"
	"    margin-left:                    35px;\r\n"
	"    margin-right:                   5px;\r\n"
	"    /* margin:                         5px; */\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	".select{\r\n"
	"    background:                     rgba(72, 130, 255, 0.2);\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"/* #paTable tr:first-child{\r\n"
	"    background:                    rgba(72, 130, 255, 0.2); \r\n"
	"} */\r\n"
	"\r\n"
	"#paTable tr:nth-child(2n){\r\n"
	"    border-top:                     dotted thin;\r\n"
	"    border-bottom:                  dotted thin;\r\n"
	"}\r\n"
	"\r\n"
	"#paTable td{\r\n"
	"    width:                          400px;\r\n"
	"    height:                         50px;\r\n"
	"    \r\n"
	"    padding:                        7px 10px;\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn{ /* Up/Dwon \xed\x99\x94\xec\x82\xb4\xed\x91\x9c"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    \r\n"
	"    /* border-spacing:                 0px 50px 0px; */\r\n"
	"    height:                         245px;\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn td{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    margin-bottom:                  20px;\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn button{ \r\n"
	"    width:                          70px;\r\n"
	"    height:                         70px\r\n"
	"}\r\n"
	"\r\n"
	"/* -- section : area2(\xec\x98\xa4\xeb\xa5\xb8\xec\xaa\xbd"") ------------ */\r\n"
	"#area2{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    float:                          right;\r\n"
	"    width:                          250px;    \r\n"
	"    height:                         340px;             \r\n"
	"}\r\n"
	"\r\n"
	"#area2 button{ /* \xec\x8b\x9c\xec\x9e\x91"", \xec\xa0\x95\xec\xa7\x80"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    background:                     white;\r\n"
	"    border:                         solid thin rgb(0, 0, 145);\r\n"
	"    width:                          130px;\r\n"
	"    height:                         85px;\r\n"
	"    border-radius:                  10px;\r\n"
	"    /* margin:                         50px 0px 0px 0px; */\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    1000;\r\n"
	"}\r\n"
	"\r\n"
	"#startBtn{\r\n"
	"    margin:                         100px 0px 40px 45px;\r\n"
	"}\r\n"
	"\r\n"
	"#stopBtn{\r\n"
	"    margin:                         0px 0px 0px 45px;\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#prevBtn{\r\n"
	"    margin-right:                   45px;          \r\n"
	"}\r\n";


const char *GetCSSPages::pSimulation =
	"section{\r\n"
	"    display:                        inline-block;\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#txtLine{ /* \xed\x96\x89\xec\x84\xa0""(\xec\x83\x81\xed\x96\x89\xec\x84\xa0""/\xed\x95\x98\xed\x96\x89\xec\x84\xa0"") */\r\n"
	"    background:                     rgb(68, 115, 195);\r\n"
	"    /* border:                         none; */\r\n"
	"    border-radius:                  10px;\r\n"
	"    width:                          150px;\r\n"
	"    height:                         50px;\r\n"
	"    margin:                         10px 0px 10px 20px;\r\n"
	"    padding:                        7px;\r\n"
	"    font-size:                      25px;\r\n"
	"    font-weight:                    800;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          white;\r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	".inforTable{ /* \xeb\x85\xb8\xec\x84\xa0\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xeb\xb0\x8f"" \xeb\xb0\xa9\xec\x86\xa1\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    background-color:               white;\r\n"
	"    border:                         solid thin navy;\r\n"
	"    border-collapse:                collapse;\r\n"
	"    /* border-spacing:                 0px; */\r\n"
	"    overflow-y:                     hidden; /* \xec\x8a\xa4\xed\x81\xac\xeb\xa1\xa4"" \xec\x88\xa8\xea\xb8\xb0\xea\xb8\xb0"" */\r\n"
	"    width:                          280px;\r\n"
	"    height:                         250px;\r\n"
	"    /* margin:                         5px; */\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	"\r\n"
	"\r\n"
	".inforTable td{\r\n"
	"    width:                          280px;\r\n"
	"    height:                         50px;\r\n"
	"    \r\n"
	"    padding:                        7px 10px;\r\n"
	"}\r\n"
	"\r\n"
	".inforTable tr:nth-child(2n){ /* \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94\xec\x9d\x98"" \xec\xa7\x9d\xec\x88\x98"" tr */\r\n"
	"    border-top:                     dotted thin;\r\n"
	"    border-bottom:                  dotted thin;\r\n"
	"}\r\n"
	"\r\n"
	"#routeList{ /* \xeb\x85\xb8\xec\x84\xa0\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    margin-left:                    25px;\r\n"
	"}\r\n"
	"\r\n"
	"#eventList{ /* \xeb\xb0\xa9\xec\x86\xa1\xeb\xa6\xac\xec\x8a\xa4\xed\x8a\xb8"" \xed\x85\x8c\xec\x9d\xb4\xeb\xb8\x94"" */\r\n"
	"    margin-left:                    10px;\r\n"
	"}\r\n"
	"\r\n"
	".select{\r\n"
	"    background:                     rgba(72, 130, 255, 0.2);\r\n"
	"}\r\n"
	"\r\n"
	".arrowBtn{ /* Up/Dwon \xed\x99\x94\xec\x82\xb4\xed\x91\x9c"" \xeb\xb2\x84\xed\x8a\xbc"" */\r\n"
	"    display:                        inline-block;\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    \r\n"
	"    /* border-spacing:                 0px 50px 0px; */\r\n"
	"    height:                         250px;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#cancBtn{\r\n"
	"    margin-right:                   40px;          \r\n"
	"}\r\n"
	"\r\n"
	"#stopBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n"
	"\r\n"
	"#startBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n";


const char *GetCSSPages::pSysInfo =
	"section{\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	".updateDiv{ /* log\xeb\xb6\x80\xeb\xb6\x84""(\xec\x99\xbc\xec\xaa\xbd""), \xeb\xb2\x84\xed\x8a\xbc\xeb\xb6\x80\xeb\xb6\x84""(\xec\x98\xa4\xeb\xa5\xb8\xec\xaa\xbd"") */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    float:                          left;\r\n"
	"    width:                          400px;\r\n"
	"    height:                         340px;\r\n"
	"    padding:                        10px;\r\n"
	"}\r\n"
	"\r\n"
	".sysLog{ /* log\xeb\xb6\x80\xeb\xb6\x84""(\xec\x99\xbc\xec\xaa\xbd"") */\r\n"
	"    border:                         solid thin navy;\r\n"
	"    border-radius:                  15px;\r\n"
	"    background-color:               white;\r\n"
	"    width:                          350px;\r\n"
	"    height:                         300px;\r\n"
	"    margin:                         20px 40px;\r\n"
	"    padding:                        10px;\r\n"
	"    \r\n"
	"}\r\n"
	"\r\n"
	".sysBtn{ /* \xeb\xb2\x84\xed\x8a\xbc\xeb\xb6\x80\xeb\xb6\x84""(\xec\x98\xa4\xeb\xa5\xb8\xec\xaa\xbd"") */\r\n"
	"    background-color:               navy;\r\n"
	"    /* border:                         none; */\r\n"
	"    border-radius:                  10px;\r\n"
	"    color:                          white;\r\n"
	"    width:                          300px;\r\n"
	"    height:                         50px;\r\n"
	"    font-size:                      20px;\r\n"
	"    margin:                         25px 50px 0px 50px;\r\n"
	"    font-size:                      23px;\r\n"
	"    font-weight:                    600;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#prevBtn{\r\n"
	"    margin-right:                   45px;          \r\n"
	"}\r\n";

const char *GetCSSPages::pTrainNumber=
	"section{\r\n"
	"    /* position:                       absolute; */\r\n"
	"    /* border:                         solid thin; */\r\n"
	"    width:                          800px;\r\n"
	"    height:                         340px;\r\n"
	"}\r\n"
	"\r\n"
	"#border{ /* section \xec\x95\x88\xec\x97\x90"" \xed\x95\x98\xec\x96\x80\xec\x83\x89"" \xed\x85\x8c\xeb\x91\x90\xeb\xa6\xac"" */\r\n"
	"    border:                         solid 5px white;\r\n"
	"    border-radius:                  20px;\r\n"
	"    margin:                         22px 40px 0px 40px;\r\n"
	"    width:                          700px;\r\n"
	"    height:                         300px;\r\n"
	"}\r\n"
	"\r\n"
	".area{ /* \xed\x95\x98\xec\x96\x80"" \xed\x85\x8c\xeb\x91\x90\xeb\xa6\xac"" \xec\x95\x88\xec\x97\x90"" '\xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8\xed\x91\x9c\xec\x8b\x9c\xec\x98\x81\xec\x97\xad""'\xea\xb3\xbc"" '\xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c\xec\x98\x81\xec\x97\xad""'\xec\x9c\xbc\xeb\xa1\x9c"" \xec\x98\x81\xec\x97\xad\xec\x9d\x84"" \xeb\x82\x98\xeb\x88\x88\xeb\x8b\xa4"" */\r\n"
	"    float:                          left;\r\n"
	"    width:                          340px;\r\n"
	"    height:                         280px;\r\n"
	"                       \r\n"
	"}\r\n"
	"\r\n"
	"#trainNumber{ /* \xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8"" */\r\n"
	"    background-color:             white;\r\n"
	"    border:                         solid thin navy;\r\n"
	"    width:                          250px;\r\n"
	"    height:                         80px;\r\n"
	"    margin:                         30px 35px;\r\n"
	"    font-size:                      60px;\r\n"
	"    text-align:                     center;\r\n"
	"}\r\n"
	"\r\n"
	".area table{ /* \xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c"" */\r\n"
	"    border-spacing:                 8px;\r\n"
	"    margin:                         20px 10px;\r\n"
	"}\r\n"
	".area table td{ /* \xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c\xec\x9d\x98"" \xec\x88\xab\xec\x9e\x90\xed\x82\xa4\xeb\x93\xa4"" */\r\n"
	"    border:                         solid thin navy;\r\n"
	"    background:                     rgb(163, 162, 162);\r\n"
	"    width:                          150px;\r\n"
	"    height:                         50px;\r\n"
	"    text-align:                     center;\r\n"
	"    color:                          white;\r\n"
	"    font-size:                      20px;\r\n"
	"    font-weight:                    500;\r\n"
	"}\r\n"
	"\r\n"
	"/* -- footer ---------------------------------------- */\r\n"
	"#cancBtn{\r\n"
	"    margin-right:                   40px;          \r\n"
	"}\r\n"
	"\r\n"
	"#okBtn{\r\n"
	"    margin-right:                   15px;\r\n"
	"}\r\n";
