#pragma once
#include "../civetweb/CivetServer.h"
#include "GetCSSPages.h"


class CTrainNumberHandle : public CivetHandler
{
public:

	bool handleGet(CivetServer *server, struct mg_connection *conn)
	{
		//UTF-8 Conversion
		//mg_connection *pComm = (mg_connection*)conn;
		//mg_header *pHeader=(mg_header*)&mg_get_request_info(conn)->http_headers[0];

		//redirection!!
		//mg_send_http_redirect(conn, , 301);

		mg_printf(conn,
			"HTTP/1.1 200 OK\r\nContent-Type: "
			"text/html\r\nConnection: close\r\n\r\n");
		mg_printf(conn,
			"  <!DOCTYPE html>\r\n"
			"  <html lang=\"ko\">\r\n"
			"        <head>\r\n"
			"            <meta charset=\"utf-8\">\r\n"
			"<style>");
		mg_printf(conn, GetCSSPages::pPISC);
		mg_printf(conn, GetCSSPages::pTrainNumber);
		mg_printf(conn, 
			"</style>\r\n"
			"            <script>\r\n"
			"                var trainId = document.querySelector(\".area td\");\r\n"
			"                var setFlag = false;\r\n"
			"\r\n"
			"                function inputNum(num){\r\n"
			"                    if((num >= '0') && (num <= '9')){ // 0~9\r\n"
			"                        if(trainNumber.value.length < 4){ \r\n"
			"                            trainNumber.value += num;\r\n"
			"                        }\r\n"
			"                    }\r\n"
			"                    else if(num == 'b'){\r\n"
			"                        if(setFlag == false){\r\n"
			"                            trainNumber.value = trainNumber.value.substring('', trainNumber.value.length-1);                \r\n"
			"                        }\r\n"
			"                    }\r\n"
			"                    else if(num == 'c'){\r\n"
			"                        trainNumber.value = ''; \r\n"
			"                        setFlag = false; \r\n"
			"                        trainNumber.style.color = \"black\";\r\n"
			"                    }\r\n"
			"                    else{ \r\n"
			"                        console.log(\"\xec\x88\xab\xec\x9e\x90"", \xeb\xb0\xb1\xec\x8a\xa4\xed\x8e\x98\xec\x9d\xb4\xec\x8a\xa4"", Clear \xec\x99\xb8\xec\x97\x90"" \xeb\x8b\xa4\xeb\xa5\xb8"" \xeb\xac\xb8\xec\x9e\x90""\")\r\n"
			"                    }\r\n"
			"\r\n"
			"                    if(trainNumber.value.length >= 4){\r\n"
			"                        document.querySelector(\"#okBtn\").disabled = false; // \xed\x99\x9c\xec\x84\xb1\xed\x99\x94""\r\n"
			"                    }\r\n"
			"                    else{\r\n"
			"                        document.querySelector(\"#okBtn\").disabled = true; // \xeb\xb9\x84\xed\x99\x9c\xec\x84\xb1\xed\x99\x94""\r\n"
			"                    }\r\n"
			"                }\r\n"
			"\r\n"
			"\r\n"
			"                function load() {\r\n"
			"                    var wsproto = (location.protocol === 'https:') ? 'wss:' : 'ws:';\r\n"
			"                    connection = new WebSocket(wsproto + '//' + window.location.host + '/wsTrainNumber');\r\n"
			"                    connection.onmessage = function (e) {\r\n"
			"                        var parseData = JSON.parse(e.data);\r\n"
			"                        var rV = parseJson(parseData);\r\n"
			"                    }\r\n"
			"                    connection.onerror = function (error) {\r\n"
			"                        alert('WebSocket error');\r\n"
			"                        connection.close();\r\n"
			"                    }\r\n"
			"                }\r\n"
			"\r\n"
			"\r\n"
			"\r\n"
			"                function confirmTrainNumber() {\r\n"
			"                    var info = { name: \"confirmTrainNumber\" , value: trainNumber.value };\r\n"
			"                    var strInfo = JSON.stringify(info);\r\n"
			"                    connection.send(strInfo);\r\n"
            "                    console.log(strInfo);\r\n"
			"                }\r\n"
			"\r\n"
			"\r\n"
			"                function parseJson(srcData)\r\n"
			"                {\r\n"
			"                    for (var i = 0; i < srcData.length; i++) {\r\n"
			"                        var temp, selTable;\r\n"
			"                        var ctrlType = srcData[i].name.substr(0, 3);\r\n"
			"                        switch (ctrlType) {\r\n"
			"                            case \"txt\":\r\n"
            "                                console.log(\"name:\" + srcData[i].name+ \", value:\" + srcData[i].value);\r\n"
			"                                temp = document.getElementById(srcData[i].name);\r\n"
			"                                temp.innerText = srcData[i].value();\r\n"
			"                                break;\r\n"
			"                            case \"ind\":\r\n"
			"                                temp = document.getElementById(srcData[i].name);\r\n"
			"                                temp.style = srcData[i].value;\r\n"
			"                                break;\r\n"
			"                            case \"grp\":\r\n"
			"                                break;\r\n"
			"                            case \"val\":\r\n"
			"                                eval(srcData[i].value);\r\n"
			"                                break;\r\n"
			"                            default:\r\n"
			"                                break;\r\n"
			"                        }\r\n"
			"                    }\r\n"
			"                }\r\n"
			"\r\n"
			"\r\n"
			"                // -- \xed\x99\x95\xec\x9d\xb8\xeb\xb2\x84\xed\x8a\xbc"" \xeb\x88\x84\xeb\xa5\xb4\xeb\xa9\xb4"" \xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8"" set \xec\x8b\x9c\xed\x82\xa4\xea\xb8\xb0"" ---------------------------------------\r\n"
			"                //document.querySelector(\"#okBtn\").onclick = function(){\r\n"
			"                //    trainNumber.style.color = \"red\"; // \xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8\xea\xb0\x80"" \xec\x84\xa4\xec\xa0\x95\xeb\x90\x98\xec\x97\x88\xeb\x8b\xa4\xeb\x8a\x94"" \xec\x9d\x98\xeb\xaf\xb8""(\xea\xb8\x80\xec\x9e\x90\xec\x83\x89"" RED)                   \r\n"
			"                 //   setFlag = true; // \xec\x84\xa4\xec\xa0\x95"" \xec\x99\x84\xeb\xa3\x8c"" flag\r\n"
			"                //}\r\n"
			"            </script>\r\n");

		mg_printf(conn,
			"            <title>PISC-\xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8\xec\x84\xa4\xec\xa0\x95""</title>\r\n"
			"  \r\n"
			"        </head>\r\n"
			"  \r\n"
			"        <body onload=\"load()\" oncontextmenu='return false' ondragstart='return false' onselectstart='return false'>\r\n"
			"            <div id=\"container\">\r\n"
			"  \r\n"
			"                <!-- header --------------------------------------------------------------- -->\r\n"
			"                <header>\r\n"
			"                    <img id=\"logo\" src=\"/app/image/Logo.png\" alt=\"\xec\x84\x9c\xec\x9a\xb8\xea\xb5\x90\xed\x86\xb5\xea\xb3\xb5\xec\x82\xac"" \xeb\xa1\x9c\xea\xb3\xa0""\">\r\n"
			"\r\n"
			"                    <span id=\"nowTime\">\r\n"
			"                        <p id=\"txtDate\">2020. 02. 04</p>\r\n"
			"                        <p id=\"txtTime\">AM 10 : 25 : 30</p>\r\n"
			"                    </span>\r\n"
			"                    <span><p id=\"headerTitle\">\xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8\xec\x84\xa4\xec\xa0\x95""</p></span>\r\n"
			"                    <hr id=\"headerLine\">\r\n"
			"                </header>\r\n"
			"  \r\n"
			"                <!-- section -------------------------------------------------------------- -->\r\n"
			"                <section>\r\n"
			"\r\n"
			"                    <div id=\"border\">\r\n"
			"                        <!-- \xec\x84\xa4\xec\xa0\x95\xed\x95\x9c"" \xec\x97\xb4\xec\xb0\xa8\xeb\xb2\x88\xed\x98\xb8"" \xed\x91\x9c\xec\x8b\x9c\xed\x95\x98\xeb\x8a\x94\xea\xb3\xb3"" -->\r\n"
			"                        <div class=\"area\">\r\n"
			"                            <input type=\"text\" id=\"trainNumber\">\r\n"
			"                        </div>\r\n"
			"\r\n"
			"                        <!-- \xec\x88\xab\xec\x9e\x90"" \xed\x82\xa4\xed\x8c\xa8\xeb\x93\x9c"" -->\r\n"
			"                        <div class=\"area\">\r\n"
			"                            <table>\r\n"
			"                                <tr>\r\n"
			"                                    <td onclick=\"inputNum('1')\">1</td><td onclick=\"inputNum('2')\">2</td><td onclick=\"inputNum('3')\">3</td>\r\n"
			"                                </tr>\r\n"
			"                                <tr>\r\n"
			"                                    <td onclick=\"inputNum('4')\">4</td><td onclick=\"inputNum('5')\">5</td><td onclick=\"inputNum('6')\">6</td>\r\n"
			"                                </tr>\r\n"
			"                                <tr>\r\n"
			"                                    <td onclick=\"inputNum('7')\">7</td><td onclick=\"inputNum('8')\">8</td><td onclick=\"inputNum('9')\">9</td>\r\n"
			"                                </tr>\r\n"
			"                                <tr>\r\n"
			"                                    <td onclick=\"inputNum('b')\">\xe2\x86\x90""</td><td onclick=\"inputNum('0')\">0</td><td onclick=\"inputNum('c')\">C</td>\r\n"
			"                                </tr>\r\n"
			"\r\n"
			"                            </table>\r\n"
			"                        </div>\r\n"
			"                    </div>\r\n"
			"\r\n"
			"                </section>\r\n"
			"              \r\n"
			"                <!-- footer --------------------------------------------------------------- -->\r\n"
			"                <footer>\r\n"
			"                    \r\n"
			"                    <button class=\"rectFootBtn\" id=\"cancBtn\" onclick=\"location.href='menu'\">\xec\x9d\xb4\xec\xa0\x84""</button>\r\n"
			"                    <button class=\"rectFootBtn\" id=\"okBtn\" onclick=\"confirmTrainNumber()\" disabled>\xed\x99\x95\xec\x9d\xb8""</button>\r\n"
			"                  \r\n"
			"                </footer>\r\n"
			"            </div>\r\n"
			"\r\n"
			"  \r\n"
			"        </body>\r\n"
			"  \r\n"
			"  </html>\r\n"

		);
		return true;
	}
};

/*
"        function load() {\r\n"
"            var wsproto = (location.protocol === 'https:') ? 'wss:' : 'ws:';\r\n"
"            connection = new WebSocket(wsproto + '//' + window.location.host + '/wsIndex');\r\n"
"            connection.onmessage = function (e) {\r\n"
"                console.log(e.data);\r\n"
"                var parseData = JSON.parse(e.data);\r\n"
"                for(var i=0;i<parseData.length;i++)\r\n"
"                {\r\n"
"                    var temp = document.getElementById(parseData[i].name);\r\n"
"                    temp.innerText = parseData[i].value;\r\n"
"                }\r\n"
"            }\r\n"
"            connection.onerror = function (error) {\r\n"
"                alert('WebSocket error');\r\n"
"                connection.close();\r\n"
"            }\r\n"
"        }\r\n"
*/
